# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 491d4c044120ddae96ee712b40b712f355087f65b486923388a9c8b414e5969546781bedb7169782b421959e8252d78243153e0ecd6e4cd9cf7926ad039c2386

test:
  secret_key_base: 9daea1eb507631c247a12abd431c4aa25ec65787005eaae7a7d169ca1113aa29c534608a694f7a8b5b6469bf3f4b4d604b6a1801df4782c343a2167e0b5b3a01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
